### ISSUE TITLE
Double scrollbars and other terrible rendering on Windows

### ISSUE THREAD

**Issue by ajayyy** [dhleong/hangr#43]
The chat seems really thin for me, making many images stretch. Could this be fatter?

![image](https://cloud.githubusercontent.com/assets/12688112/25824534/ccbc0d94-340d-11e7-9683-f87106d8ddd4.png)

**Comment by dhleong** [comment]
Haha oh boy it really doesn't render well on Windows. It was sized
expecting to not have a fixed scrollbar like that. Thanks for the report.

**Comment by ajayyy** [comment]
Oh haha, now I see the other scrollbar

**Comment by dhleong** [comment]
Yeah, on OSX the scrollbar totally fades away and overlays content when it shows up, so it is supposed to look like this:

![](https://cloud.githubusercontent.com/assets/816150/21584557/45b8f330-d07a-11e6-9f58-588cd6783070.png)

Note also how there's not supposed to be a menu bar, either.

I'm not set up to develop this project on Windows right now but I'll try to find some time to figure out what's going on.

**Comment by ajayyy** [comment]
Wow, that looks really nice. I might try to look into that stuff to if I can figure it out. If that's ok with you (doesn't​ look like you have a license so not sure).

**Comment by dhleong** [comment]
Absolutely, go for it! Haven't thought about license yet (mainly because it's just been me using and working on this) but I usually go with MIT. The hangupsjs doesn't seem to have a license either, but the lib it's a port of is MIT so... should be fine.

**Comment by ajayyy** [comment]
Ok, just double checking! Thanks.

**Comment by ajayyy** [comment]
Looks like for windows you must use ``frame: false``.

https://github.com/electron/electron/blob/master/docs/api/frameless-window.md#create-a-frameless-window

**Comment by ajayyy** [comment]
Hmm... I got a bunch of errors on building

`npm WARN deprecated tough-cookie@0.12.1: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
npm WARN deprecated wrench@1.5.4: wrench.js is deprecated! You should check out fs-extra (https://github.com/jprichardson/node-fs-extra) for any operations you were using wrench for. Thanks for all the usage over the years.
npm WARN deprecated minimatch@0.2.12: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue`

and

`npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--no-optional"
npm ERR! node v6.5.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! hangr@ postinstall: `cd node_modules/hangupsjs && ../.bin/coffee -o lib src`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the hangr@ postinstall script 'cd node_modules/hangupsjs && ../.bin/coffee -o lib src'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the hangr package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cd node_modules/hangupsjs && ../.bin/coffee -o lib src
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs hangr
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls hangr
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\hangr\hangr\npm-debug.log`

**Comment by ajayyy** [comment]
How do you build the project?

**Comment by dhleong** [comment]
I build on macOS and cross-compile for windows, so dunno about windows, but for dev work I run `scripts/repl` to compile the clojurescript, followed by `grunt launch` to start electron. `scripts.sh` worked for me just now. Maybe try updating to npm 4? I've been using npm 4 and node 7 to develop

**Comment by ajayyy** [comment]
Oh ok, so I would want to edit the clojure files and not the java script files.

**Comment by ajayyy** [comment]
Oh, node 7, I will update my node.js version.

**Comment by dhleong** [comment]
The javascript stuff controls how the windows render, so actually you might need to do that

**Comment by ajayyy** [comment]
Ok, good. Got the window bar disappeared, but I think I'll have to add a manual x button.

For this I just edited the js in the release build (in the resources section) :), for easy testing for now.

![image](https://cloud.githubusercontent.com/assets/12688112/25926798/48c24d6a-35bf-11e7-8f4f-89d57d638891.png)

**Comment by dhleong** [comment]
Nice!

Unfortunately I think I misspoke a bit. The frame rendering is handled in JS, but the contents are all in cljs. That window specifically is in `hangr/views/conversation.cljs`

**Comment by ajayyy** [comment]
Ok, I just adjusted the initialization code of ``BrowserWindow`` and added a line to the css to remove the scrollbar. I also have edited the position function in the docked-window.js to do ``y-=40`` only on Windows to appear above the taskbar (this would be bad for people with taskbar hidden or in a different location but it's better than it being behind it).

Now I don't know where to start on adding a button to the top for closing the windows...

**Comment by dhleong** [comment]
To add a button to the UI you'll need to read a bit on [hiccup](https://github.com/weavejester/hiccup) and [reagent](http://reagent-project.github.io/). I think it's very elegant once you know what's going on, but if you're not familiar with clojure it might be sort of a lot. 

The other option is you can put up a PR with the changes you made, and I can work on the buttons myself.

**Comment by ajayyy** [comment]
Ok, I did add a PR. But first I think I'm gonna try on my own. I've never worked with clojure, but learning is fun :smile:! I just realized, You can check the PR if you want just to check out if my changes break it on OSX.

**Comment by dhleong** [comment]
Sounds good! I hope you come to love clojure as much as I do :)

This is a pretty good way to get started if you want to learn the language:

http://clojurescriptkoans.com/

**Comment by ajayyy** [comment]
Sorry to bother you with all of these questions, but the project is for eclipse right? That's what I saw in the project file, but I got a clojure plugin and it won't recognize it as a project. Is it for another IDE?

**Comment by dhleong** [comment]
Sorry, no, I don't use an IDE for clojure, just good old Vim with some good
plugins.

**Comment by dhleong** [comment]
Yep, you're looking for `conversation-header` in `views/conversation.cljs`

**Comment by ajayyy** [comment]
Also, I can't find the location of the icons. Are they defined somewhere?

**Comment by dhleong** [comment]
https://material.io/icons

Just take the name as shown there, replaces spaces with `-` and turn it into a keyword, and pass that to the `[icon]` widget.

**Comment by dhleong** [comment]
Hi @ajayyy sorry for taking so very long to get to this. Using:

```
::-webkit-scrollbar { 
    display: none; 
}
```

completely disables scrollbars, which is not desired since on OSX they nicely appear on scroll. I haven't had a chance to test on windows yet, but I did notice that `#app-container` has `overflow-y: scroll;` in addition to `#conversation #events-container`. That may be the source of the double scrollbars....

**Comment by ajayyy** [comment]
Ah, I see. Thanks for getting back to me. You don't have to focus on fixing it anymore if you don't want to, I have stopped using hangouts now so wouldn't really use the features. If there ends up being another Windows user who wants to use the program, I'd be happy to help fix it.
