### ISSUE TITLE
Group Names

### ISSUE THREAD

**Issue by ajayyy** [dhleong/hangr#44]
Not sure if this is possible, but could you get group names? Right now it just lists the people in the chat. Thanks for making this awesome program!

**Comment by dhleong** [comment]
Not sure, but I'll look into it! If the data I get includes them it'd be easy to render, but take a bit of extra work to set them in-app. Like most things, you'll probably have to use the official client to set them for a while.

**Comment by ajayyy** [comment]
Makes sense, just wanted to mention it. Thanks!

**Comment by dhleong** [comment]
Turns out I was trying to support it, I was just looking in the wrong place for the group name. Should be fixed with the new v0.6.3

**Comment by ajayyy** [comment]
That's awesome! Thank you!
